import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/Navbar";
import Footer from "@/components/ui/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { QueryProvider } from "@/providers/queryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // [ ] : Safe guard you api endpoints (for eg : ddos)

    return (
        <html lang="en">
            <body className={inter.className}>
                <ClerkProvider>
                    <QueryProvider>
                        <Navbar />
                        {children}
                        <Footer />
                        <ReactQueryDevtools initialIsOpen={false} />
                    </QueryProvider>
                </ClerkProvider>
            </body>
        </html>
    );
}
